server:
  port:
    8080
    
spring:
  datasource:
    url: jdbc:h2:mem:product
    username: sa
    password: 
    
  h2:
    console.enabled: true
    
  jpa:
    hibernate:
      ddl_auto: update
      
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    